# -*- mode:toml; -*-
[module.app-pthread_bench]
    appfiles = [ "app/init.cc", "app/main.cc" ]
    provides = [ "app/init.elf" ]
    requires = [ "crtbegin"]

    makefile_head = '''
TARGETS += app/init.elf
APP_CXXFLAGS += -fopenmp
APP_CXXFLAGS += $(BENCH_APP_FLAGS)
'''

    makefile_body = '''
app/init.elf: $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(CRTFILES_OBJ)
	$(APP_CXX) $(APP_LDFLAGS) $(APP_CXXFLAGS) -nostdlib -o $@ runtime/start.o runtime/crtbegin.o $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(APP_LIBS) runtime/crtend.o
	$(NM)  $@ | cut -d " " -f 1,3 | c++filt -t > init.sym
	$(OBJDUMP) -dS $@ | c++filt > init.disasm
	$(STRIP) $@
'''

