# -*- mode:toml; -*-
[module.app-hipsmixer]
    appfiles = [ "app/init.cc" ]
    provides = [ "app/init.elf" ]
    requires = [ "crtbegin"]

    makefile_head = '''
HIPS_PATH := ../applications/hipsmixer/HiPSmixer/
HIPS_MAKEFILE := ../makefile.mythos
HIPS_RUN_PATH := $(HIPS_PATH)/run/ODTLES-IMEX-3R-Serial-Channel.a

#HIPS_TARGETS := aN=X tN=X pN=ODT* NTHREADS=2 openmp 
HIPS_TARGETS := aN=X tN=X pN=ODT* $(HIPSARGS)

TARGETS += app/init.elf
APP_CXXFLAGS += -fopenmp -O3
APP_CXXFLAGS += $(MYTHOSFLAGS)
'''

    makefile_body = '''
app/init.elf: $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(CRTFILES_OBJ)
	make -C $(HIPS_PATH) -f $(HIPS_MAKEFILE) purge
	make -j `nproc` -C $(HIPS_PATH) -f $(HIPS_MAKEFILE) $(HIPS_TARGETS)
	$(APP_CXX) $(APP_LDFLAGS) $(APP_CXXFLAGS) -nostdlib -o $@ runtime/start.o runtime/crtbegin.o $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(HIPS_RUN_PATH) $(APP_LIBS) runtime/crtend.o
	$(NM)  $@ | cut -d " " -f 1,3 | c++filt -t > init.sym
	$(OBJDUMP) -dS $@ | c++filt > init.disasm
	$(STRIP) $@
'''

